### ISSUE TITLE
Certificate download doesn't work

### ISSUE THREAD

**Issue by michalmasrna1** [ZdruzenieSTROM/mas-problem#123]
```
class CompetitorCertificateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        competitor = Competitor.get_competitor(self.request.user, self.object)
        if competitor.certificate is not None:
            return FileResponse(competitor.certificate)
        return redirect('competition:after-game')
```

`CompetitorCertificateView` has no object, `Competitor.get_competitor` needs to be called with game as the second argument.

I propose the `/moj-diplom` url should also carry the primary key of the game for which the competitor want their certificate.

In addition, the certificates are uploaded to the `diplomy` folder, but there is no path specified for serving those static files.

**Comment by kovacspe** [comment]
> In addition, the certificates are uploaded to the diplomy folder, but there is no path specified for serving those static files.
Certificates are served dynamically, in order to check permissions
