### ISSUE TITLE
Pridat prezeranie starsich vysledkov

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/mas-problem#13]

**Comment by michalmasrna1** [comment]
v ramci tohto treba aj opravit tie messages po konci hri a tak podobne, kde su zatial zakomentovane odkazy na archiv

**Comment by kovacspe** [comment]
@michalmasrna1 Zalozil som branch a nafeedoval tam data akurat neviem ako z toho spravit nejaky rozumne vyzerajuci dropdown. Vies to prosim dokoncit?
